### ISSUE TITLE
Switch of read out registers when resetting

### ISSUE THREAD

**Issue by itofficeeu** [Miceuz/PlantWateringAlarm#12]
When I have the sensor hocked up to I2C and I use the reset on the top of the sensor, can it happen that the read out registers switches. Moisture then is read from the register for light and the other way around.

I do not know if this depends on the producer. I do not now if this can be fixed by software. I can reveal that my hardware does not respond with temperature data. So maybe is it only the product I have in hand? - Be aware from where you buy, if the temperature sensing is important. Try out a small quantity first.

One should be prepared for sanitizing the switched data afterwards or maybe even build in an automatic sanitation.

The moisture values runs from around 300 to close to 500 (covered by hand). The light values from zero when full lid by for instance a flashlight, to close to 9000 when I cover it with my one hand (could maybe be more when absolute dark is reached?). - I do not know if these figures are different on hardware from other producers.

**Comment by DrBabbage** [comment]
I might have the same issue. Have you found a fix?

**Comment by itofficeeu** [comment]
Nope. Dropped working with the sensor.

**Comment by Miceuz** [comment]
Chirp is not ment for proper installations, just play around with a pot nearby. For proper performance look into standalone I2C sensor
