### ISSUE TITLE
Sensor damaged by soil

### ISSUE THREAD

**Issue by git-torrent** [Miceuz/PlantWateringAlarm#13]
Hello,

my sensor got damaged by soil (paint peeled off). Readings go from 200 to 2000, I can't use it anymore. I guess the paint reacts with sourer soil.
![20190609_112312](https://user-images.githubusercontent.com/12293198/59157451-1f427300-8aab-11e9-961e-52ff98bd9352.jpg)
Thank you

**Comment by Miceuz** [comment]
Hello,

Can you please give more information:
 * What is the version written on the sensor?
 * How long did it take before failure?

**Comment by Miceuz** [comment]
Also can you plese make a picture of the damage on the other side of the sensor?

**Comment by git-torrent** [comment]
Hello, for sure I am sending both sides. In two separate emails

[image: 20190611_195831.jpg]
All the best

Pavol Ostertag

po 10. 6. 2019 v 13:57 odesílatel Albertas Mickėnas <
notifications@github.com> napsal:

**Comment by git-torrent** [comment]
I am sending both sides, for sure. I guess, the version is 2.7.6
![20190611_195831](https://user-images.githubusercontent.com/12293198/59360842-24185880-8d31-11e9-8e20-3f5e49d7237b.jpg)
![20190611_195825](https://user-images.githubusercontent.com/12293198/59360850-24b0ef00-8d31-11e9-82b7-74e7b0bd489b.jpg)

**Comment by Miceuz** [comment]
How long did it take before failure?
And can you please elaborate if the sensor was re-inserted into soil a lot?

**Comment by git-torrent** [comment]
The sensor was inserted into soil in October 2018. Back then, values were ca 420 for freshly watered soil and ca 160 for dry soil (I pulled the sensor out). So I calibrated it to range 150 - 400. During winter the sensor remained in the soil. When I started watering again (in March), the readings were always 100% - fully wet. Only when heats started and soil became dry, I started to wonder why the sensor still reads "fully wet". That was the first time I pulled it out. I cleaned the soil from the tip and the result is in the pictures.

The soil is for blackcurrant so it is maybe little bit acidic (Ph6) when fertilized.

**Comment by Miceuz** [comment]
Hi, 
Thank you for your report. Yes, sensors are not totally bullet proof. Especially when it comes to freezing ground. Can you ship me the sensor for examination? I would ship you a replacement. Please contact me via email - mic at wemakethings dot net
