### ISSUE TITLE
Light calibration

### ISSUE THREAD

**Issue by YodaDaCoda** [Miceuz/PlantWateringAlarm#18]
I may be understanding the code incorrectly, but I think that since `lightThreshold` is initialised to `65530` but `isLightNotCalibrated()` checks for `65535` that the light will never be calibrated.

https://github.com/Miceuz/PlantWateringAlarm/blob/937454452ec9647b5ac41bcbe988b7f8bb27b8a3/src/main.c#L308

https://github.com/Miceuz/PlantWateringAlarm/blob/937454452ec9647b5ac41bcbe988b7f8bb27b8a3/src/main.c#L321-L323

**Comment by Miceuz** [comment]
https://github.com/Miceuz/PlantWateringAlarm/blob/937454452ec9647b5ac41bcbe988b7f8bb27b8a3/src/main.c#L337

It's beeing read from eeprom, it will result in 65535 in case on uninitialized eeprom.
