### ISSUE TITLE
Fluctuating Sensor data on Raspberry Pi on standalone and chirp

### ISSUE THREAD

**Issue by DrBabbage** [Miceuz/PlantWateringAlarm#19]
I use both sensors hooked up individually to a raspberry pi without pull up resistor on a 2 meter cable.
Its a desperate efford to get this soil moisture sensor working with mycodo.

![image](https://user-images.githubusercontent.com/66676158/179478568-b04fcdd3-fbac-4ce8-bafa-01e97d2c532e.png)

The readout is fluctuating between a around 6000 to 240 to 0. Atm its in the soil.

Here is the data communication with the raspberry pi read with a logic analizer.

`W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x98·W[0x20]·0x9C·W[0x20]·0x98·W[0x20]·0x48·W[0x20]·0x4C·W[0x20]·0x48·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0xD8·W[0x20]·0xDC·W[0x20]·0xD8·W[0x20]·0x48·W[0x20]·0x4C·W[0x20]·0x48·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09·W[0x20]·0x29·W[0x20]·0x2D·W[0x20]·0x29·W[0x20]·0x09·W[0x20]·0x0D·W[0x20]·0x09...
`
I hooked up a saleae
[soil moisture sensor.zip](https://github.com/Miceuz/PlantWateringAlarm/files/9130918/soil.moisture.sensor.zip)

The chirp I often fail to bring in i2c mode. Is there a trick to do this from the start and skip the whole chirping?

The chirp hw version is 1.1 and the sensor 2.78
I will write some documentation on this.

My sensors are Soil moisture sensor 2.7.8 , 2.7.6 and chirp 2.4

Moisture  | Temp   | Brightness
-------------------------------
38 -39.6% | 0.0°C | 15617
1 -46.9% | 0.0°C | 106
302 12.2% | 31.7°C | 106
304 12.5% | 31.7°C | 106
306 12.9% | 31.7°C | 105
305 12.7% | 31.7°C | 106
306 12.9% | 31.7°C | 105
304 12.5% | 31.6°C | 105
0 -47.1% | 0.0°C | 15616
15617 3015.1% | 1254.5°C | 12801
304 12.5% | 31.7°C | 104

I tried flashing a firmware on one with make hex make program which executed successfully and set the fuses but now it doesn't turn on anymore. I have a second one though.

![image](https://user-images.githubusercontent.com/66676158/179549002-cc8df32a-7293-4a23-9aac-9644e5ba6843.png)

I found some more sensors from you, they also don't work in mycodo so I opened an issue here https://github.com/kizniche/Mycodo/issues/1216 regarding that. 

I tried chirp-rpi out and the output is much more stable but it too get these high values from time to time and after some waiting, reading fails completely and i2cdetect takes ages and ultimately fails to detect the sensor.
Also I got rid of the cable so that its now 8cm long.

![image](https://user-images.githubusercontent.com/66676158/179553581-ac1eeb14-ffeb-45b2-9632-63c780c19b49.png)

**Comment by DrBabbage** [comment]
,

**Comment by Miceuz** [comment]
Hi, 

2 meters is really stretching it. Things to try 

- *use pullups* you can start from 4k7 and try going a bit lower.
- slow down I2C clock
- use shorter cable
