### ISSUE TITLE
Are External I2C Pullup Resistors Required?

### ISSUE THREAD

**Issue by vicatcu** [Miceuz/PlantWateringAlarm#7]
Hey, sorry this is not really an issue per say, except maybe a documentation issue. Are external pull-up resistors required if you are using the stand-alone sensor version to interface with an Arduino over I2C? 

I don't see any in the schematics, but maybe I missed something. If indeed they aren't there, might not be a horrible idea to put pads on the PCB to (optionally) populate them.

**Comment by Miceuz** [comment]
Idea being that there could be other devices on the bus and bus design is a higher level task, I think master should provide pullups. Say, its totally a designer decision on the size of pullup resistors.

On January 19, 2018 5:09:41 PM GMT+02:00, Victor Aprea <notifications@github.com> wrote:
>Hey, sorry this is not really an issue per say, except maybe a
>documentation issue. Are external pull-up resistors required if you are
>using the stand-alone sensor version to interface with an Arduino over
>I2C? 
>
>I don't see any in the schematics, but maybe I missed something. If
>indeed they aren't there, might not be a horrible idea to put pads on
>the PCB to (optionally) populate them. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Miceuz/PlantWateringAlarm/issues/7

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vicatcu** [comment]
Yup, I dig it, and I agree in general. The question is really can you hook it up (as the only device on the I2C bus) to an Arduino Uno directly and communicate successfully? For example using [this library](https://github.com/Apollon77/I2CSoilMoistureSensor) or the example code on [your page](https://wemakethings.net/chirp/). It wouldn't hurt to put a reminder to developers that these external resistors _might_ be necessary in a given application, perhaps in the README on this repo.

**Comment by Miceuz** [comment]
Yes, you can hook it up directly to Arduino. Their internal pullups by default are on and are enough to test.

On January 19, 2018 5:57:39 PM GMT+02:00, Victor Aprea <notifications@github.com> wrote:
>Yup, I dig it, and I agree in general. The question is really can you
>hook it up (as the only device on the I2C bus) to an Arduino Uno
>directly and communicate successfully? For example using [this
>library](https://github.com/Apollon77/I2CSoilMoistureSensor) or the
>example code on [your page](https://wemakethings.net/chirp/). It
>wouldn't hurt to put a reminder to developers that these external
>resistors _might_ be necessary in a given application.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Miceuz/PlantWateringAlarm/issues/7#issuecomment-359007069

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
