### ISSUE TITLE
i2c power usage

### ISSUE THREAD

**Issue by luismanson** [Miceuz/PlantWateringAlarm#8]
Hello, thanks for this device and your time, I plan on read this from an esp board, can i keep the coin cell? I do not know how much will it last. 
Also, i plan on having more than one device on the bus, how do i change the addess?

thanks :)

**Comment by Miceuz** [comment]
Hi,

For bigger installations consider the sensor-only version, either I2C or RS485. 
https://github.com/Miceuz/i2c-moisture-sensor
https://github.com/Miceuz/rs485-moist-sensor
