### ISSUE TITLE
Discharge through transistors

### ISSUE THREAD

**Issue by mundodisco8** [Miceuz/PlantWateringAlarm#9]
Hi,
I've read your writeup about using transistors to discharge C1 faster, but on the latest version I can find in your repo, I see no trace of those trasnsistors. Have you moved to a simpler design? If so, can you explain why?

Thanks for sharing your project!

**Comment by Miceuz** [comment]
Hi,

Transistors worked in simulation, but are too slow when run at high frequency. Besides, it works fine enough.
